Repository rubygarage/rubygarage.github.com, pull requests merged in 2019-11, with the labels that each got.

#197 Feature | PEO-799 | [Automation workshop] FFaker
  automation-qa/ffaker.markdown
Labels: needs review

#201 Feature | [Automation workshop] Pre programming course
  slides/preprogramming-course.markdown
Labels: needs review

#196 Feature | PEO-796 | [Automation workshop] Install Rspec
  assets/images/install-rspec/rspec.png
  slides/install-rspec.markdown
Labels: in progress

#195 Feature | PEO-797 | [Automation workshop] Rails test types
  assets/images/types-of-test/rails-test-types.png
  slides/types-of-test.markdown
Labels: needs review

#199 Feature | PEO-801 | [Automation workshop] Rules of Rspec
  slides/rules-of-rspec.markdown
Labels: needs review

#198 Feature | PEO-800 | [Automation workshop] Factory Bot
  slides/factory-bot.markdown
Labels: needs review

#193 Feature | PEO-795 | [Automation workshop] Rails structure
  assets/images/rails-structure/Ruby_On_Rails_Logo.png
  assets/images/rails-structure/structure.png
  slides/rails-structure.markdown
Labels: needs review

#200 Feature | PEO-802 | Add slides about SitePrism
  automation-qa/site-prism.markdown
Labels: needs review

#194 Feature | PEO-798 | [Automation workshop] Capybara
  slides/capybara.markdown
Labels: needs review

#203 Feature | [Automation workshop] Guide Rspec
  assets/images/install-rspec/rspec.png
  assets/images/rails-structure/Ruby_On_Rails_Logo.png
  assets/images/rails-structure/structure.png
  assets/images/types-of-test/rails-test-types.png
  slides/automation-qa/capybara.markdown
  slides/automation-qa/database-cleaner.markdown
  slides/automation-qa/factory-bot.markdown
  slides/automation-qa/ffaker.markdown
  slides/automation-qa/index.markdown
  slides/automation-qa/preprogramming-course.markdown
  slides/automation-qa/rails-structure.markdown
  slides/automation-qa/rspec.markdown
  slides/automation-qa/site-prism.markdown
  slides/rules-of-rspec.markdown
Labels: reviewed

#207 Feature | [Automation workshop] Add simplecov, restructure RSpec slides
  slides/automation-qa/capybara.markdown
  slides/automation-qa/factory-bot.markdown
  slides/automation-qa/index.markdown
  slides/automation-qa/rails-structure.markdown
  slides/automation-qa/rspec.markdown
  slides/automation-qa/simple-cov.markdown
  slides/automation-qa/site-prism.markdown
Labels: needs review
