Repository rubygarage/rubygarage.github.com, pull requests merged in 2020-04, with the labels that each got.

#219 Feature | PEO-913 | [GraphQL] Update types slides
  slides/graphql.markdown
Labels: reviewed

#213 Add slides for Introduction and Batch Loading in GraphQL
  assets/images/graphql/lazy_loading.png
  assets/images/graphql/without_lazy_loading.png
  slides/graphql.markdown
Labels: in progress

#224 Feature | PEO-918 | [GraphQL] Add pagination slides
  slides/graphql.markdown
Labels: reviewed

#223 Feature | PEO-916 | [GraphQL] Update error handling slides
  slides/graphql.markdown
Labels: reviewed

#226 Feature | AWS | IAM slides
  assets/images/aws/iam/mfa_1.png
  assets/images/aws/iam/mfa_2.png
  assets/images/aws/iam/mfa_3.png
  assets/images/aws/iam/mfa_4.png
  slides/aws/iam.markdown
Labels: needs review

#221 Feature | AWS EC2 slides
  assets/images/aws/instance_lifecycle.png
  assets/images/aws/regions_aws.png
  assets/images/aws/security_group_rules.png
  slides/aws/ec2.markdown
Labels: needs review

#228 | Feature | AWS | ECS slides
  assets/images/aws/ecs/alb.png
  assets/images/aws/ecs/architecture.png
  assets/images/aws/ecs/blue_green.png
  assets/images/aws/ecs/cloud_watch.png
  assets/images/aws/ecs/ecr.png
  assets/images/aws/ecs/elb.png
  assets/images/aws/ecs/fargate.png
  assets/images/aws/ecs/logo.png
  assets/images/aws/ecs/rolling_update.png
  slides/aws/ecs.markdown
  slides/aws/index.markdown
Labels: needs review

#227 Feature | AWS | VPC slides
  assets/images/aws/architecture-of-vpc.png
  slides/aws/index.markdown
  slides/aws/vpc.markdown
Labels: needs review
