Repository rubygarage/rubygarage.github.com, pull requests merged in 2020-11, with the labels that each got.

#240 Extend docker slides
  slides/docker/docker.markdown
Labels: needs review

#241 Update Ruby Basics slides
  slides/ruby-basics.markdown
Labels: reviewed

#244 Improve Rails routes slides
  slides/routes.markdown
Labels: reviewed

#242 Fix Rack slides
  slides/rack.markdown
Labels: reviewed

#245 Update | Introduction slides
  slides/introduction.markdown
Labels: Content Update, reviewed
